FROM public.ecr.aws/lambda/python:3.14

WORKDIR /asset

RUN python -m pip install --upgrade pip

COPY lambda_function.py /asset/lambda_function.py
COPY validators /asset/validators

RUN python -m pip install --no-cache-dir --target /asset email-validator psycopg2-binary pydantic
